src/components/CheckClientVersion/CheckClientVersion.tsx
src/services/ClientVersionHelper.ts
src/state/ducks/Parameters.ts

Don't prompt user to reset the client, after updating nodes #225

---

config/webpack.config.dev.js
package.json
src/components/AttestedClaimsListView/AttestedClaimsListView.tsx
src/components/ChainStats/ChainStats.tsx
src/components/DelegationDetailView/DelegationDetailView.tsx
src/components/Utilities/Utilities.tsx
src/components/withSelectAttestedClaims/withSelectAttestedClaims.tsx
src/containers/Tasks/AcceptDelegation/AcceptDelegation.tsx
src/containers/Tasks/CreateDelegation/CreateDelegation.tsx
src/containers/Tasks/ImportDelegation/ImportDelegation.tsx
src/containers/Tasks/RequestAttestation/RequestAttestation.tsx
src/services/AttestationWorkflow.ts
src/services/ClientVersionHelper.ts
src/services/DelegationsService.ts
src/services/DidService.ts
src/utils/CtypeUtils/CTypeUtlis.spec.ts
tsconfig.json
yarn.lock

This PR fixes code, which is not working after the polkadot/api update in the SDK.
NOTE: The SDK still needs to be published and updated here.
- Checkout latests SDK
- link it into this codebase with yalc
- try out with the utilities functions in the GUI
- click through everything according to tutorial: https://kilt.io/wp-content/uploads/2019/05/KILT_client_walkthrough_v2019-May-13.pdf

chore: updated code after polkadot/api update

---

src/utils/CtypeUtils/CTypeUtlis.spec.ts
src/utils/CtypeUtils/CtypeInputSchema.ts
src/utils/CtypeUtils/CtypeUtils.ts

Added the CType input model as a schema
yarn test

fix: added CType input schema

---

.github/workflows/release.yml
.gitignore
.npmrc
Dockerfile

This PR adds a release workflow to github actions
Only testable by making a release

ci: releases workflow

---

src/components/SelectDelegationAction/SelectDelegationAction.tsx

undeifned identity inside the QR code.

fix: undefined identity fix

---

src/utils/PublicIdentity/Encoding.ts

Made the uniform encoding
Check if it works.

refactor: change the qrcode to be uniform when encoding

---

src/components/KiltToken/KiltToken.tsx
src/components/MyClaimListView/MyClaimListView.tsx

Showing transaction fees with units and the balance with units. 
Additionally, having a way to change the unit type to increase the amount of token changed.

feat: token denomination units

---

src/components/DevTools/DevTools.anticov.ts
src/components/DevTools/DevTools.tsx
src/components/DevTools/DevTools.wallet.tsx
src/components/IdentityView/IdentityView.tsx
src/components/KiltToken/KiltToken.tsx
src/containers/Balance/Balance.tsx
src/services/BalanceUtilities.tsx
src/state/ducks/Balances.ts

When hovering over the token amount it shows the full amount. 
Transfer or use the faucet

feat: display token amounts with units and hover shows full token amount

---

src/services/DidService.ts
src/types/Contact.d.ts

Sign did with sdk when registering

---

package.json
src/services/AttestationService.ts
yarn.lock

Fixes the name of verify function from the sdk

fix: attestation check valid

---

src/containers/Tasks/SubmitTerms/SubmitTerms.tsx

Originally, we had to have a delegation or an attested claim to be able to send the submit terms.
Run through sending a quote.

refactor: quote can be sent with submit terms

---

src/components/DevTools/DevTools.anticov.ts
src/components/DevTools/DevTools.ctypes.tsx
src/components/DevTools/DevTools.delegations.tsx
src/components/DevTools/DevTools.wallet.tsx
src/containers/CtypeCreate/CtypeCreate.tsx
src/services/AttestationService.ts
src/services/BalanceUtilities.tsx
src/services/DelegationsService.ts
src/services/DidService.ts

Changes to the types and the way we handle the DIDs.
Update to substrate 2.0
Yarn start and go through the workflow.

fix: tx SDK changes and Substrate 2.0 update

---

src/containers/WalletAdd/WalletAdd.tsx

Bug with adding and removing identities delete the contacts.
Add and remove identity that has a contact.

fix: bug with contacts

---

src/components/ContactPresentation/ContactPresentation.tsx
src/components/Dashboard/Dashboard.tsx
src/components/DelegationDetailView/DelegationDetailView.tsx
src/components/DevTools/DevTools.tsx
src/components/DevTools/DevTools.wallet.tsx
src/components/IdentityView/IdentityView.tsx
src/components/MyDelegationsInviteModal/MyDelegationsInviteModal.tsx
src/components/SelectDelegationAction/SelectDelegationAction.tsx
src/components/Utilities/Utilities.tsx
src/containers/Balance/Balance.tsx
src/containers/ClaimView/ClaimView.tsx
src/containers/DelegationsView/DelegationsView.tsx
src/containers/MyQuotesList/MyQuotesList.tsx
src/containers/QuoteView/QuoteView.tsx
src/containers/Tasks/AcceptDelegation/AcceptDelegation.tsx
src/containers/Tasks/AttestClaim/AttestClaim.tsx
src/containers/Tasks/RequestAcceptDelegation/RequestAcceptDelegation.tsx
src/containers/Tasks/RequestAttestation/RequestAttestation.tsx
src/containers/Tasks/SubmitTerms/SubmitTerms.tsx
src/containers/WalletAdd/WalletAdd.tsx
src/services/AttestationService.ts
src/services/AttestationWorkflow.ts
src/services/ClientVersionHelper.ts
src/services/ContactRepository.ts
src/services/DelegationsService.ts
src/services/MessageRepository.tsx
src/state/ducks/Wallet.ts

Added button to register and delete DID on the dashboard.
Change the store management of selected Identities with the wallet.
Fixed issues of the selected wallet being undefined. Now throws an error if selected identity not handled.
Add and delete a did within the dashboard.

feat: added did register to dashboard

---

package.json
src/components/ChainStats/ChainStats.tsx
src/components/DelegationNode/DelegationNode.tsx
src/components/DevTools/DevTools.anticov.ts
src/components/DevTools/DevTools.ctypes.tsx
src/components/DevTools/DevTools.delegations.tsx
src/containers/CtypeCreate/CtypeCreate.tsx
src/containers/Tasks/CreateDelegation/CreateDelegation.tsx
src/services/AttestationService.ts
src/services/BalanceUtilities.tsx
src/services/DelegationsService.ts
src/services/DidService.ts
yarn.lock

updated version 33 
Spin up and run through the envrionment

feat: sdk update version 33

---

package.json
src/components/DevTools/DevTools.anticov.ts
src/components/DevTools/DevTools.wallet.tsx
src/containers/WalletAdd/WalletAdd.tsx
src/state/ducks/Wallet.ts
src/types/Contact.d.ts
yarn.lock

added the advanced options and able to switch between the different algorithms

feat: release ready

---

package.json
yarn.lock

Upgrading to the latest release candidate of the SDK
Run through

feat: release candidate SDK 4

---

src/components/DevTools/DevTools.tsx

Bug found in utilities 
Reload https://demo.devnet.kilt.io/utilities

fix: utilities bug

---

src/components/AttestedClaimVerificationView/AttestedClaimVerificationView.tsx

The claim contents were not shown at all.
- Make a claim and get it attested
- Request this claim and look at it

fix: show claim contents again

---

src/services/DelegationsService.ts

fix: delegation revoke signandsend

---

package.json
src/components/DelegationNode/DelegationNode.tsx
src/components/DevTools/DevTools.anticov.ts
src/components/DevTools/DevTools.ctypes.tsx
src/components/MessageDetailView/MessageDetailView.tsx
src/containers/CtypeCreate/CtypeCreate.tsx
src/containers/Tasks/RequestClaimsForCType/RequestClaimsForCType.tsx
src/services/AttestationService.ts
src/services/BalanceUtilities.tsx
src/services/DelegationsService.ts
src/services/DidService.ts
src/services/MessageRepository.tsx
src/state/ducks/Claims.ts
yarn.lock

This PR prepares the release of the demo-client with the sdk 0.21.0 release candidate.

chore: release v0.22.0
