- src/components/IdentityView/IdentityView.tsx
Appends the address for window.open
Also say KILT address instead of address in the wallet and dashboard
- create identity
- request tokens on ./Wallet
- should open faucet with ?(selected identity's address here) as url parameter
> feat: append address when requesting tokens

- src/components/AttestationStatus/AttestationStatus.tsx
- src/components/AttestedClaimVerificationView/AttestedClaimVerificationView.tsx
- src/components/CTypePresentation/CTypePresentation.tsx
- src/components/ClaimDetailView/ClaimDetailView.tsx
- src/components/DevTools/DevTools.attestations.tsx
- src/components/DevTools/DevTools.claims.tsx
- src/components/DevTools/DevTools.ctypes.tsx
- src/components/MyClaimCreateView/MyClaimCreateView.tsx
- src/components/MyClaimListView/MyClaimListView.tsx
- src/components/SelectAttestedClaims/SelectAttestedClaims.tsx
- src/containers/ClaimCreate/ClaimCreate.tsx
- src/containers/ClaimView/ClaimView.tsx
- src/containers/CtypeCreate/CtypeCreate.tsx
- src/containers/CtypeView/CtypeView.tsx
- src/containers/Tasks/RequestAttestation/RequestAttestation.tsx
- src/containers/Tasks/RequestLegitimation/RequestLegitimation.tsx
- src/containers/Tasks/SubmitLegitimations/SubmitLegitimations.tsx
- src/containers/Tasks/Tasks.tsx
- src/services/AttestationService.ts
- src/services/AttestationWorkflow.ts
- src/services/MessageRepository.tsx
- src/state/ducks/Claims.ts
- src/utils/CtypeUtils/CTypeUtlis.spec.ts
- src/utils/CtypeUtils/CtypeUtils.ts
This is just replacing constructor calls of refactored constructors and changing property names accordingly.
I'll create a second ticket if we want to change our descriptions aswell hash to roothash and cType to cTypeHash.
> SDK Compatibility

- .github/workflows/aws-dev.yml
- .github/workflows/tests.yml
- Dockerfile
- Dockerfile.devnet
- package.json
- task-definition.json
- yarn.lock
This PR converts our AWS Codepipeline tasks to github actions.
It also adds support for node v12.
- Look at the successfully running tests
- See the automatically deployed devnet demo client in aws
> ci: use github actions instead of aws CI

- .env.devnet
- .env.production
Prepended HTTPS to BOTH `REACT_APP_SERVICE_HOST` and `PUBLIC_URL`.
Initially, the issues were caused by `REACT_APP_SERVICE_HOST` but I thought I might as well fix `PUBLIC_URL` too.
Make sure that the build scripts run properly.
> feat: prepended protocol to URLs

- src/services/AttestationService.ts
- yarn.lock
related to https://github.com/KILTprotocol/sdk-js/pull/239
Check the PR in the sdk-js repo
> fix: take delegation id from request

- src/components/MessageDetailView/MessageDetailView.tsx
- src/containers/Tasks/AttestClaim/AttestClaim.tsx
- src/containers/Tasks/SubmitLegitimations/SubmitLegitimations.tsx
- src/services/AttestationWorkflow.ts
- src/services/MessageRepository.tsx
This PR allows using public identities on messages instead of contacts for "submit terms" and "submit attestation".
- Use the anticov app
> feat: use publicidentity as alternative to contact

- src/components/DevTools/DevTools.anticov.ts
- src/components/DevTools/DevTools.tsx
- src/components/DevTools/data/anticov.json
- src/services/BalanceUtilities.tsx
- src/services/DelegationsService.ts
- src/services/MessageRepository.tsx
- src/utils/setupAnticov.ts
Because the devnet is reset on commits to develop (mashnet-node), Timo requested we set up a script to write the CType and delegation needed for AntiCov back to chain. We figured this would best be situated on the demo-client, where it now serves an additional purpose: Users can invite themselves to the AntiCov delegation tree with the click of a button.
> Anticov delegation setup button

- README.md
Had a question inside the RIOT channel regarding the local setup. 
Noticed there was no mention of the Prototype serivces.
Let us think of stuff.
> refactor: inclusion in prototype services readme

- .github/workflows/aws-dev.yml
- .github/workflows/tests.yml
- Dockerfile
- Dockerfile.devnet
- docker-compose.yml
This uses a development version of the sdk and Portablegabi, published to [GitHub Packages](https://github.com/orgs/KILTprotocol/packages) to build devnet images and to run tests builds.
> ci: test with latest sdk

- .github/workflows/aws-dev.yml
- .npmrc.github
- Dockerfile.devnet
The above mentioned PR had issues with building devnet images. I was under the assumption that the setup node action creates a `.npmrc` & `.yarnrc` file in the working directory, but I was mistaken. To fix this, I added a `.npmrc` template to the repository, with which I overwrite the `.npmrc` in the workflow.
This time, I will demonstrate that it works by committing a [stub of the workflow that builds on this branch](https://github.com/KILTprotocol/demo-client/actions/runs/156534620), then revert. The container should successfully complete the `yarn upgrade` step and bump the sdk to a develop version, which we can tell from a commit hash included in the version number.
> fix: devnet build with latest sdk

- src/containers/ClaimView/ClaimView.tsx
- src/services/DidService.ts
Necessary changes on the demo client when replacing `TxStatus` with `SubmittableResult` in the SDK (see ticket).
- checkout sdk on branch `rf-drop-TxStatus` & run `yalc publish`
- on demo client, link sdk with `yalc add '@kiltprotocol/sdk-js'`
- `yarn install`, then run & test via bootstrap tools & manual steps
> refactor: SubmittableResult instead of TxStatus

- src/services/AttestationWorkflow.ts
Changes to the naming caused the terms not to be submitting and rendering. 
Go through the request terms, with either or a delegation and legitimation.
> fix: bug fixes

- src/containers/DelegationCreate/DelegationCreate.tsx
When creating a Delegation root node switching accounts would not re-render the new account.
Create a new delegation and switch accounts.
> fix: delegation root node bug when switching identities

- src/containers/MessageView/MessageView.tsx
- src/services/MessageRepository.tsx
> Provide signed messageId when removing message by Id

- package.json
- src/components/DevTools/DevTools.anticov.ts
- src/components/DevTools/DevTools.tsx
- src/components/DevTools/DevTools.wallet.tsx
- src/components/KiltToken/KiltToken.tsx
- src/containers/Balance/Balance.tsx
- src/services/BalanceUtilities.tsx
- yarn.lock
Removes the demo-client based unit denominations and conversions and instead uses the sdk based utils.
publish local sdk
start local demo client and services and check for units and balance behaviour.
> feat: use sdk for unit denomination and conversion

- .github/sdk-update-issue-template.md
- .github/workflows/kube-dev.yml
- .github/workflows/test-sdk-update.yml
- .github/workflows/tests.yml
- .npmrc
- .npmrc.github
- Dockerfile
- package.json
- yarn.lock
This PR removes the dependency to github packages and just uses npm as repo.
It also adds another workflow, which can be triggered, whenever there is a new SDK dev release, which tests the demo client with it. The normal test just uses the specified version in package.json / yarn.lock.
Tests are expected to fail for now. Will be handled after this PR was merged.
> feat: use npm dev package for sdk

- package.json
- src/components/DevTools/DevTools.anticov.ts
- src/components/DevTools/DevTools.ctypes.tsx
- src/components/DevTools/DevTools.delegations.tsx
- src/containers/CtypeCreate/CtypeCreate.tsx
- src/services/AttestationService.ts
- src/services/BalanceUtilities.tsx
- src/services/ContactRepository.ts
- src/services/CtypeRepository.ts
- src/services/DelegationsService.ts
- src/services/DidService.ts
- src/services/MessageRepository.tsx
- yarn.lock
Adds compatibility for the multitx functionalities, does not use re-try functionality, waits for IS_IN_BLOCK.
> feat: MultiTx & SDK Compatibility, non re-try

- src/containers/WalletAdd/WalletAdd.tsx
- src/services/DidService.ts
- src/types/Contact.d.ts
At the moment we don't check if an identity has a DID when adding the identity to the Demo-client
Add an identity with tokens to generate a DID.
Delete said identity and re-add with a mnemonic.
> feat: DID fetch on creating an identity

- src/containers/Tasks/RequestTerms/RequestTerms.tsx
When requesting terms without providing a claim, the user gets a blocking error notification.
Create a CType and request terms without a claim.
> fix: Requesting terms 

- src/services/AttestationService.ts
As far as I can tell, the issue was related to improper copying of the AttestedClaim object before removing properties (which internally just calls `delete` on them). This led to removal on the original object in state as well as on the copy.
Proceed as in the ticket; this should no longer be the case.
> fix: claim property removal during claim submission affected stored claims

- src/components/DelegationNode/DelegationNode.tsx
The demo-client allows users to click the "Revoke all attestations" button even for nodes to which no attestations are linked. 
But trying to revoke all attestations by a delegation node would block the client if the delegation node had no attestations.
This fix introduces an early exit when no attestations are found (with the UI remaining unblocked), and notifies the user. 
Simply create a new DelegationNode, then click the "Revoke All Attestations" button on it. This would formerly block the UI.
> fix: revoking attestations on node w/o attestations blocked ui

- src/components/DelegationNode/DelegationNode.tsx
- src/components/DevTools/DevTools.anticov.ts
- src/components/DevTools/DevTools.ctypes.tsx
- src/components/DevTools/DevTools.delegations.tsx
- src/containers/CtypeCreate/CtypeCreate.tsx
- src/containers/Tasks/CreateDelegation/CreateDelegation.tsx
- src/services/AttestationService.ts
- src/services/BalanceUtilities.tsx
- src/services/DelegationsService.ts
- src/services/DidService.ts
Switching to `submitTxWithResign` fixes the issue of extrinsic errors going unnoticed (this uses defaults for `rejectOn`).
Try different transactions that must fail - attesting on a revoked delegationNode etc.
> fix: tx submisson

- src/state/ducks/Claims.ts
Fixes an issue where the revocation status was not correctly displayed in the claims list because the state was updated incorrectly.
This is the result of a state update before the fix: 
As you can see, the `revoked` property was set on the wrong object, one level too high.
Attest a claim, revoke it, then navigate to the claims list. While the revoked claim may still show a green check mark, it should switch to a red `x` after you entered the claim detail view once (clicking on the claim alias, then going back to the list view).
> fix: display attestation status in claims list

- .github/workflows/release.yml
Removes steps to set new image on mashnet in the release workflow.
Deployment to devnet is still triggered on push to develop.
> chore: do not attempt deployment on release
